[package]
name = "CrossChainToken"
version = "0.0.1"
authors = ["Your Name"]

[addresses]
std = "0x1"
aptos-stdlib = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
cross_chain = "_"
token_bridge = "_"
wormhole = "_"
deployer = "_"
deployer_aux = "_"
aux = "_"

[dev-addresses]
cross_chain = "0x66"
token_bridge = "0x576410486a2da45eee6c949c995670112ddf2fbeedab20350d506328eefc9d4f"
wormhole = "0x5bc11445584a763c1fa7ed39081f1b920954da14e04b32440cba863d03e19625"
wrapped_coin = "0xf4f53cc591e5190eddbc43940746e2b5deea6e0e1562b2bba765d488504842c7"
deployer = "0x0108bc32f7de18a5f6e1e7d6ee7aff9f5fc858d0d87ac0da94dd8d2a5d267d6b"
aux = '0x4c8e0dc1b53b7759c9d8998685453a0e06565f054f3635a18d4928520eec676d'
deployer_aux = '0x8686'

[dependencies.TokenBridge]
git = "https://github.com/wormhole-foundation/wormhole.git"
rev = "main"
subdir = "aptos/token_bridge"

[dependencies.Wormhole]
git = "https://github.com/wormhole-foundation/wormhole.git"
rev = "main"
subdir = "aptos/wormhole"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "6f83bc6d02207298b2dee91133d75538789bf582"
subdir = "aptos-move/framework/aptos-framework"